In [55]:
import scrapy 
from scrapy.crawler import CrawlerProcess

In [57]:
import numpy as np
x=list(range(10))

In [62]:
 l = [1,2,3]

In [66]:
np.array(x)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
l.append('H')
print(l)

[1, 2, 3, 'H', 'H']


In [70]:
l[3]="HASHEM"

In [73]:
x = np.array(l)

In [75]:
x = np.array(list(range(10)))

In [80]:
x.data.itemsize

8

In [85]:
x.put(1,89)

In [86]:
x

array([ 0, 89,  2,  3,  4,  5,  6,  7,  8,  9])

In [87]:
x[::2]

array([0, 2, 4, 6, 8])

In [88]:
x[2:4]

array([2, 3])

In [90]:
x[:] = 22

In [91]:
x

array([22, 22, 22, 22, 22, 22, 22, 22, 22, 22])

In [92]:
x.mean()

22.0

In [93]:
(x,y)=(7,8)

In [94]:
r = (x, 7)

In [95]:
r

(7, 7)

In [99]:
r[0]

7